### ISSUE TITLE
Get Flags on patient dashboard After successive Call

### ISSUE THREAD

**Issue by sherrif10** [johnsonandjohnson/openmrs-distro-cfl#3]
Hello @pwargulak @aagrawa4 , 
Still on the flags , we have managed to set our query in our manage flags. And configured our widget for showing  flags on the dashboard, However one thing that is missing is the connectivity between patient responses and our view controller widget, i think we either missing some configurations in the patient flag widget 
Looking forward for your suggestions.

**Comment by pwargulak** [comment]
Hi @sherrif10 
What do you mean by lack of connectivity? 
As I remember, you have a patient flag which reads actor responses (messages_actor_response) made during a symptom reporting call. And what is the view controller widget?

@druchniewicz @mjozefow

**Comment by sherrif10** [comment]
What i mean is the configurations between when a call is made and the response, currently our configuration to do with sql works perfectly, but if a call is made, a response inform of symptom is is not pushed to the dashboard.

**Comment by aagrawa4** [comment]
Hi Sharif,

Lets discuss this in a call at 3:30 EAT.

Thanks,
Avinash

From: MAGEMBE SHARIF ***@***.***>
Sent: Monday, November 14, 2022 9:40 AM
To: johnsonandjohnson/openmrs-distro-cfl ***@***.***>
Cc: Agrawal, Avinash [ITSUS Non J&J] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [johnsonandjohnson/openmrs-distro-cfl] Get Flags on patient dashboard After successive Call (Issue #3)


What i mean is the configurations between when a call is made and the response, currently our configuration to do with sql works perfectly, but if a call is made, a response inform of symptom is is not pushed to the dashboard.

**Comment by sherrif10** [comment]
Alright thanks.

**Comment by druchniewicz** [comment]
This is not a bug. Correct combination of callflow + SQL query flag has to be used.
