### ISSUE TITLE
ActorId is  not  captured  in cfl_calls  table when a  call  is  initiated (registration/consent call)

### ISSUE THREAD

**Issue by AnnetKabuye** [johnsonandjohnson/openmrs-distro-cfl#4]
Dear  Team, 
I  am experiencing  an  issue  where  actorId is  not  captured  in cfl_calls  table  for  initiated  calls. I set up  an  Coonect for  Life  instance  where a  survey  is taken. Therefore  all  calls  are  initiated,  they  are no  scheduled  calls.  I  noticed  that  for  all  these  calls no  actorIds  were  captured  yet  we  have  to map  call  details  to  a  participant. Please  advise  on  how  we  can  have  actorId  captured in  this  table  for  initiated  calls  moving  forward.

Regards,
Annet

**Comment by druchniewicz** [comment]
actorId was indeed not captured in cfl_calls table for consent call. In the latest CfL code we can use "TriggerMessage" mechanism (which is mainly supposed to be a feature helpful for testing but it can be used for real cases as well). 
Backend for TriggerMessage - https://github.com/johnsonandjohnson/openmrs-module-messages/blob/main/omod/src/main/java/org/openmrs/module/messages/web/controller/TriggerMessageController.java
FE:
* https://github.com/johnsonandjohnson/openmrs-module-messages/blob/main/omod/src/main/webapp/fragments/triggerMessageDialog.gsp
* https://github.com/johnsonandjohnson/openmrs-module-messages/blob/main/omod/src/main/webapp/resources/scripts/triggerMessage.js

The idea is that you configure a message e.g. Health Tip and it creates a scheduled task for now and call/sms is triggered immediately. As it is a scheduled task, actorId field will be saved in cfl_calls table.
