### ISSUE TITLE
Openmrs-CFL Release 7.0 failing to build successfully

### ISSUE THREAD

**Issue by hkaluuma** [johnsonandjohnson/openmrs-distro-cfl#5]
Dear Team,
I am experiencing some challenges on building an instance of CFL on my local virtual machine. The previous versions of CFL till 5.0 were building successfully with ease however version 7.0 is failing with the details below:

When I tail the logs using:  **docker logs -f --tail 1000 cfl_web_1** , I get the repeated results to the ones below for different Concept# numbers. **Any assistance or advice you can give me will be highly appreciated.**

INFO - LoggingAdvice.invoke(116) |2023-04-18 13:24:29,020| In method ConceptService.saveConceptReferenceTerm. Arguments: ConceptReferenceTerm=422303009,
INFO - LoggingAdvice.invoke(116) |2023-04-18 13:24:29,041| In method ImportService.updateConceptWithoutValidation. Arguments: Concept=Concept #4785,
INFO - LoggingAdvice.invoke(156) |2023-04-18 13:24:29,042| Exiting method updateConceptWithoutValidation
INFO - LoggingAdvice.invoke(116) |2023-04-18 13:24:29,058| In method ImportService.updateConceptWithoutValidation. Arguments: Concept=Concept #4759,

**When I try to load the UI it builds but ends on update database task.**
![image](https://user-images.githubusercontent.com/44634574/232796278-c1931bb7-9ba4-433b-816e-3427d6cf17a5.png)

**Comment by druchniewicz** [comment]
This is not a bug. We introduced a mechanism that loads a large package of concepts (~50k) during system startup. It can take long time (even few hours) when system starts successfully. Keep in mind that is only one-time action, so the next system restarts will take a normal time.
